//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP_12._2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimation
    {
        public int ID { get; set; }
        public int ID_subject { get; set; }
        public Nullable<int> Estimation1 { get; set; }
        public int Semester { get; set; }
        public int ID_user { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual User User { get; set; }
    }
}
