//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP_12._2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_log
    {
        public int ID { get; set; }
        public System.DateTime Login_date { get; set; }
        public System.DateTime Logout_date { get; set; }
        public int ID_user { get; set; }
    
        public virtual User User { get; set; }
    }
}
