//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP_12._2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins_and_passwords
    {
        public int ID { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual User User { get; set; }
    }
}
